{% set name = "sqlglotrs" %}
{% set version = "0.2.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sqlglotrs-{{ version }}.tar.gz
  sha256: 50c0592a22cbb989b968e8e931085c2aa75f6c3a3ee22473490fb806352b9f94

build:
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('rust') }}
    - maturin >=1.4,<2.0                     # [build_platform != target_platform]
  host:
    - python
    - maturin >=1.4,<2.0
    - pip
  run:
    - python


test:
  imports:
    - sqlglotrs
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tobymao/sqlglot
  dev_url: https://github.com/tobymao/sqlglot/tree/main/sqlglotrs
  summary: SQLGlot tokenizer implementation in Rust
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
