{% set name = "sqlglotrs" %}
{% set version = "0.2.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sqlglotrs-{{ version }}.tar.gz
  sha256: b0baf1cd79f2c5d985f188c6f0d43403b4e0d24b395e67ea41ff4c96d8175cb1

build:
  skip: true  # [py<37]
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 2

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('rust') }}
    - maturin >=1.4,<2.0                     # [build_platform != target_platform]
    - cargo-bundle-licenses
  host:
    - python
    - maturin >=1.4,<2.0
    - pip
  run:
    - python


test:
  imports:
    - sqlglotrs
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tobymao/sqlglot
  dev_url: https://github.com/tobymao/sqlglot/tree/main/sqlglotrs
  summary: SQLGlot tokenizer implementation in Rust
  license: MIT
  license_file:
    - THIRDPARTY.yml
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
